### ISSUE TITLE
Monorepo

### ISSUE THREAD

**Issue by armaniferrante** [project-serum/serum-dex-ui#35]
Potentially merge this repo at some point with https://github.com/project-serum/serum-js, using `yarn` workspaces + `lerna`.

**Comment by askmike** [comment]
I would be very much against that: That module also runs on nodejs, and people are already depending on it for nodejs trading software. For example: https://gitlab.com/OpinionatedGeek/samm

Combining both means a lot of frontend package bloat on the node side.

**Comment by armaniferrante** [comment]
We definitely don't want to break existing packages, but using a monorepo is orthogonal to package bundle size. The only thing a monorepo would break are projects using git dependencies (rather than published npm deps), and we could avoid breaking such projects by just creating a new repo, if we really wanted to. Am I missing something?

**Comment by askmike** [comment]
> In case it wasn't clear, I'm not proposing to combine these two packages.

Ah wops I might have misunderstood. My only issues are with bundling everything in a single package - so that everyone using serum-js as an npm dependency needs to pull all of this in:

https://github.com/project-serum/serum-dex-ui/blob/4194a7aa1701ad8bcf88e6d060b4b7ff0fda760e/package.json#L7-L33


---

As long as that doesn't happen it sounds good to me.

**Comment by armaniferrante** [comment]
@askmike I 100% agree. That definitely should not happen.

**Comment by armaniferrante** [comment]
We've initialized a mono repo for *new* packages here https://github.com/project-serum/serum-ts.

**Comment by armaniferrante** [comment]
Closing this issue. If we decide to do this, we can make a new issue in `serum-ts`.
